"""MAX messenger WebSocket protocol opcodes.

Reference: APK v26.11.0 decompilation (sources/ru/ok/tamtam/api/d.java).
"""


class Opcode:
    # Connection
    PING = 1
    DEBUG = 2
    RECONNECT = 3
    ANALYTICS = 5
    INIT = 6

    # Auth flow
    PROFILE = 16
    AUTH_REQUEST = 17
    AUTH = 18
    LOGIN = 19
    LOGOUT = 20
    SYNC = 21
    CONFIG = 22
    AUTH_CONFIRM = 23
    AUTH_LOGIN_RESTORE_PASSWORD = 101
    AUTH_VALIDATE_PASSWORD = 107
    AUTH_VALIDATE_HINT = 108
    AUTH_VERIFY_EMAIL = 109
    AUTH_CHECK_EMAIL = 110
    AUTH_CREATE_TRACK = 112
    AUTH_CHECK_PASSWORD = 113
    PASSWORD_AUTH = 115  # AUTH_LOGIN_CHECK_PASSWORD in APK
    AUTH_LOGIN_PROFILE_DELETE = 116
    TOKEN_REFRESH = 158  # OK_TOKEN in APK
    AUTH_CALL_INFO = 256
    AUTH_CHECK_SCENARIO = 263
    QR_AUTH_INIT = 288
    QR_AUTH_POLL = 289
    QR_AUTH_COMPLETE = 291

    # Stickers / Assets
    PRESET_AVATARS = 25
    GET_STICKER_SETS = 26
    STICKER_SYNC = 27
    ANIMOJI = 28
    ASSETS_ADD = 29
    ASSETS_REMOVE = 259
    ASSETS_MOVE = 260
    ASSETS_LIST_MODIFY = 261

    # Contacts
    GET_CONTACTS = 32
    CONTACT_ADD = 33
    CONTACT_UPDATE = 34
    CONTACT_PRESENCE = 35
    CONTACT_LIST = 36
    CONTACT_SEARCH = 37
    CONTACT_MUTUAL = 38
    CONTACT_PHOTOS = 39
    CONTACT_SORT = 40
    CONTACT_CREATE = 41
    CONTACT_VERIFY = 42
    REMOVE_CONTACT_PHOTO = 43
    OWN_CONTACT_SEARCH = 44
    CONTACT_INFO_EXTERNAL = 45
    CONTACT_INFO_BY_PHONE = 46

    # Chats
    GET_CHATS = 48
    GET_MESSAGES = 49
    MARK_READ = 50
    GET_MEDIA_MESSAGES = 51
    DELETE_CHAT = 52
    GET_CHATS_UPDATES = 53
    CLEAR_CHAT = 54
    UPDATE_CHAT = 55
    CHECK_CHAT_LINK = 56
    JOIN_CHAT = 57
    LEAVE_CHAT = 58
    GET_CHAT_MEMBERS = 59
    CLOSE_CHAT = 61
    CREATE_CHAT = 63
    SUBSCRIBE_CHAT = 75
    UPDATE_CHAT_MEMBERS = 77
    GET_BOT_COMMANDS = 144
    CHAT_HIDE = 196
    GET_FOLDERS = 272
    FOLDERS_GET_BY_ID = 273
    FOLDERS_UPDATE = 274
    FOLDERS_REORDER = 275

    # Search
    SEARCH = 60
    SEARCH_CHATS = 68
    SEARCH_MESSAGES = 73
    SEARCH_COUNT = 197

    # Messaging
    SEND_MESSAGE = 64
    TYPING = 65
    DELETE_MESSAGE = 66
    EDIT_MESSAGE = 67
    FORWARD_MESSAGE = 69
    MSG_SHARE_PREVIEW = 70
    GET_MESSAGE = 71
    SEARCH_TOUCH = 72
    GET_MESSAGE_STATS = 74
    CHAT_PIN_SET_VISIBILITY = 86
    MSG_DELETE_RANGE = 92
    GET_LAST_MENTIONS = 127

    # Uploads
    GET_IMAGE_UPLOAD_URL = 80
    GET_STICKER_UPLOAD_URL = 81
    GET_VIDEO_UPLOAD_URL = 82
    GET_FILE_UPLOAD_URL = 87
    GET_FILE_DOWNLOAD_URL = 88

    # Media / Call links
    GET_VIDEO = 83
    VIDEO_CHAT_CREATE_JOIN_LINK = 84
    GET_MUSIC = 84  # Deprecated alias — APK says this is VIDEO_CHAT_CREATE_JOIN_LINK

    # Link previews
    GET_LINK_INFO = 89
    GET_MESSAGE_LINK = 90
    MSG_CONSTRUCT = 94

    # Sessions
    GET_SESSIONS = 96
    CLOSE_SESSION = 97

    # Phone binding
    PHONE_BIND_REQUEST = 98
    PHONE_BIND_CONFIRM = 99
    UNBIND_OK_PROFILE = 100

    # Video calls
    GET_INBOUND_CALLS = 103
    EXTERNAL_CALLBACK = 105
    VIDEO_CHAT_START = 76
    INITIATE_CALL = 78
    GET_CALL_HISTORY = 79
    VIDEO_CHAT_JOIN = 102
    VIDEO_CHAT_MEMBERS = 195

    # Complaints
    CHAT_COMPLAIN = 117
    SEND_CALLBACK = 118
    SUSPEND_BOT = 119
    COMPLAIN_REASONS_GET = 162

    # Location
    LOCATION_STOP = 124
    LOCATION_SEND = 125
    LOCATION_REQUEST = 126

    # File checks
    CHECK_FILE_UPLOAD = 136

    # Drafts
    DRAFT_SAVE = 176
    DRAFT_DISCARD = 177

    # Reactions
    REACT = 178
    CANCEL_REACTION = 179
    GET_REACTIONS = 180
    GET_DETAILED_REACTIONS = 181
    CHAT_REACTIONS_SETTINGS_SET = 257
    REACTIONS_SETTINGS_GET_BY_CHAT_ID = 258

    # Sticker creation
    STICKER_CREATE = 193
    STICKER_SUGGEST = 194

    # Social
    GET_COMMON_CHATS = 198
    GET_USER_SCORE = 201

    # Server push (cmd=0 from server)
    PUSH_NEW_MESSAGE = 128
    PUSH_TYPING = 129
    PUSH_MARK = 130
    PUSH_CONTACT = 131
    PUSH_PRESENCE = 132
    PUSH_CONFIG = 134
    PUSH_CHAT = 135
    PUSH_ATTACH = 136
    PUSH_INCOMING_CALL = 137
    PUSH_VIDEO_CHAT_COMMAND = 138
    PUSH_CONTACT_SORT = 139
    PUSH_MSG_DELETE_RANGE = 140
    PUSH_CALLBACK_ANSWER = 143
    PUSH_MSG_CONSTRUCT = 146
    PUSH_LOCATION = 147
    PUSH_LOCATION_REQUEST = 148
    PUSH_ASSETS_UPDATE = 150
    PUSH_DRAFT = 152
    PUSH_DRAFT_DISCARD = 153
    PUSH_MSG_DELAYED = 154
    PUSH_REACTIONS_CHANGED = 155
    PUSH_YOU_REACTED = 156
    PUSH_FOLDERS = 277
    PUSH_BANNERS = 292


class Cmd:
    REQUEST = 0
    RESPONSE = 1
    PUSH = 2
    ERROR = 3
